package org.example;// Generated by Selenium IDE

import lombok.extern.slf4j.Slf4j;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.Map;
import java.util.Set;

@Slf4j
public class SerfRegularTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  public SerfRegularTest(WebDriver driver, Map<String, Object> vars, JavascriptExecutor js) {
    this.driver = driver;
    this.vars = vars;
    this.js = js;
  }

  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }

  public void serfRegular() {
    log.info("Start serfing with regular");
    Integer times = 0;
    for(; ;) {
      driver.get("https://aviso.bz/work-serf");
      driver.manage().window().setSize(new Dimension(1280, 720));
      driver.findElement(By.xpath("//div[4]/table/tbody/tr/td[2]/div/a")).click();
      {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
        wait.until(ExpectedConditions.textToBe(By.linkText("Приступить к просмотру"), "Приступить к просмотру"));
      }
      try {
        Thread.sleep(5000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
      vars.put("window_handles", driver.getWindowHandles());
      driver.findElement(By.linkText("Приступить к просмотру")).click();
      vars.put("win6679", waitForWindow(2000));
      vars.put("root", driver.getWindowHandle());
      driver.switchTo().window(vars.get("win6679").toString());
      try {
        Thread.sleep(50000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
      driver.switchTo().frame(0);
      driver.findElement(By.linkText("Подтвердить просмотр")).click();
      try {
        Thread.sleep(5000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
      driver.close();
      driver.switchTo().window(vars.get("root").toString());
      try {
        Thread.sleep(10000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
      times++;
      log.info("Serf Regular counter: " + times);
    }
  }
}
