package org.example;// Generated by Selenium IDE

import org.openqa.selenium.*;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.Map;
import java.util.Set;
public class WatchYoutubeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  public WatchYoutubeTest(WebDriver driver, Map<String, Object> vars, JavascriptExecutor js) {
    this.driver = driver;
    this.vars = vars;
    this.js = js;
  }

  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }

  public void watchYoutube() {
    System.out.println("Start watching youtube videos");
    Integer times = 0;
    for(; ; ) {
      driver.get("https://aviso.bz/work-youtube");
      driver.manage().window().setSize(new Dimension(1280, 720));
      driver.findElement(By.xpath("//span[contains(@title,'youtube.com/watch')]")).click();
      {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
        wait.until(ExpectedConditions.textToBe(By.cssSelector(".go-link-youtube"), "Приступить к выполнению"));
      }
      try {
        Thread.sleep(2000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
      vars.put("window_handles", driver.getWindowHandles());
      driver.findElement(By.cssSelector(".go-link-youtube")).click();
      vars.put("win6679", waitForWindow(2000));
      vars.put("root", driver.getWindowHandle());
      driver.switchTo().window(vars.get("win6679").toString());
      driver.switchTo().frame(0);
      try {
        Thread.sleep(1000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
      driver.switchTo().defaultContent();
      driver.switchTo().frame(0);
      {
        WebElement element = driver.findElement(By.cssSelector(".ytp-large-play-button"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
      }
      driver.findElement(By.xpath("//div[@id=\'movie_player\']/div[4]")).click();
      try {
        Thread.sleep(1000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
      driver.switchTo().defaultContent();
      vars.put("timer", driver.findElement(By.xpath("//span[@id=\'tmr\']")).getText());
      vars.put("timerIncr", js.executeScript("return (parseInt(arguments[0]) + 5) *1000;", vars.get("timer")));
      System.out.println("Timer val = "+  vars.get("timer").toString());
      System.out.println("TimerIncr val = "+ vars.get("timerIncr").toString());
      try {
        Thread.sleep(Integer.parseInt(vars.get("timerIncr").toString()));
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
      vars.put("replayVideoTxt", js.executeScript("return document.body.textContent.indexOf(\'Запустите видео ещё раз, чтобы YouTube не списал ваш просмотр\') >= 0"));
      System.out.println("Replay video txt = "+ vars.get("replayVideoTxt").toString());
      if ((Boolean) js.executeScript("return (arguments[0])", vars.get("replayVideoTxt"))) {
        driver.switchTo().frame(0);
        {
          WebElement element = driver.findElement(By.cssSelector(".ytp-large-play-button"));
          Actions builder = new Actions(driver);
          builder.moveToElement(element).perform();
        }
        driver.findElement(By.xpath("//div[@id=\'movie_player\']/div[4]")).click();
        driver.switchTo().defaultContent();
        try {
          Thread.sleep(5000);
        } catch (InterruptedException e) {
          e.printStackTrace();
        }
      }
      driver.close();
      driver.switchTo().window(vars.get("root").toString());
      try {
        Thread.sleep(2000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
      System.out.println("Watched youtube videos counter: " + times);
    }
  }
}
